### ISSUE TITLE
Error when no features detected

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/RoogleVision#1]
Hi Flovv, nice work with the package!

Someone left this issue on googleAuthR:  https://github.com/MarkEdmondson1234/googleAuthR/issues/32 that perhaps you may be better placed to solve.

Let me know if there is anything I can do to help googleAuthR's end.  I suspect how it handles non-JSON content may have been an issue, but perhaps solved in the latest update [(0.3.0)](https://github.com/MarkEdmondson1234/googleAuthR/blob/master/NEWS.md) with the new `option(googleAuthR.rawResponse)` flag.

**Comment by flovv** [comment]
Hi Mark,

thanks for letting me know.
I fixed it on my side.
checking for ncol(pp$content$responses) >0 solves the issue.

Best,
Florian
